project_name: client_youtube

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy
builds:
  # ----------------------------------------
  # base
  - id: linux-amd64-build-base
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/client_base/main.go
    ldflags:
      - -s -w --extldflags "-static -fpic" -X main.AppVersion=v{{ .Version }}

  - id: linux-armv7-build-base
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 7
    main: ./cmd/client_base/main.go
    ldflags:
      - -s -w --extldflags "-static -fpic" -X main.AppVersion=v{{ .Version }}

  - id: linux-arm64-build-base
    goos:
      - linux
    goarch:
      - arm64
    main: ./cmd/client_base/main.go
    ldflags:
      - -s -w --extldflags "-static -fpic" -X main.AppVersion=v{{ .Version }}

  - id: windows-build-base
    goos:
      - windows
    goarch:
      - amd64
    main: ./cmd/client_base/main.go
    ldflags:
      - -s -w --extldflags "-static -fpic" -X main.AppVersion=v{{ .Version }}
  # ----------------------------------------
  # youtube
  - id: linux-amd64-build-youtube
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/client_youtube/main.go
    ldflags:
      - -s -w --extldflags "-static -fpic" -X main.AppVersion=v{{ .Version }}

  - id: linux-armv7-build-youtube
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - 7
    main: ./cmd/client_youtube/main.go
    ldflags:
      - -s -w --extldflags "-static -fpic" -X main.AppVersion=v{{ .Version }}

  - id: linux-arm64-build-youtube
    goos:
      - linux
    goarch:
      - arm64
    main: ./cmd/client_youtube/main.go
    ldflags:
      - -s -w --extldflags "-static -fpic" -X main.AppVersion=v{{ .Version }}

  - id: windows-build-youtube
    goos:
      - windows
    goarch:
      - amd64
    main: ./cmd/client_youtube/main.go
    ldflags:
      - -s -w --extldflags "-static -fpic" -X main.AppVersion=v{{ .Version }}

archives:
  - id: archive
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^TestData:"
      - "^TestCode:"
      - "^assets:"
