project_name: machine_translator_client

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy
builds:
  - id: build-base
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    main: ./cmd/client_base/main.go
    ldflags:
      - -s -w --extldflags "-static -fpic" -X main.AppVersion=v{{ .Version }}

archives:
  - id: archive
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^TestData:"
      - "^TestCode:"
      - "^assets:"
